on: [push]

jobs:
  compile_cv_job:
    runs-on: ubuntu-latest
    name: A job to compile CV
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile CV action step
        uses: ./
        id: compile
      - name: Setup config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit CV pdf
        run: |
          git add main.pdf
          git commit -m "Add main.pdf"
          git push