name: Compile CV and publish to GH pages

on:
  push:
    branches:
      - main

jobs:
  compile_cv_job:
    runs-on: ubuntu-latest
    name: A job to compile CV and commit pdf to pdf_branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile CV action step
        run: |
          docker build -t cv .
          docker run --name CV cv
      - name: Setup config
        run: |
          git config user.name "Mikhail Gorelyi"
          git config user.email "gorelmich@yahoo.com"
      - name: Commit CV pdf
        run: |
          docker cp CV:/main.pdf .
          git checkout -b pdf_branch
          git add main.pdf
          git commit -m "Add main.pdf"
          git push pdf_branch